services:
  - type: web
    name: universal-iptv-player
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
